alastair_cookie/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home, impressum, logout_view, tutorial
from .forms import MyLoginForm, MyPasswordChangeForm

urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^home/$', home, name='home'),
    url(r'^help/$', tutorial, name='help'),
    url(r'^impressum/$', impressum, name='impressum'),
    url(r'^login/$', auth_views.login, {'authentication_form':MyLoginForm, 'extra_context':{'heading':'Login', 'pagetitle':'Login'}}),
    url(r'^password_change/$', auth_views.password_change, {'template_name':'registration/login.html', 'post_change_redirect':'/password_change/done/', 'password_change_form':MyPasswordChangeForm, 'extra_context':{'heading':'Change Password', 'pagetitle':'Change Password'}}),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^password_change/done/$', auth_views.password_change_done, {'template_name':'registration/login.html', 'extra_context':{'heading':'Password changed', 'message':'Your password was changed successfully!'}}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^', include('cooking.urls', namespace='cooking'), name='cooking'),
    url(r'^$', home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cooking/allergen/urls.py
from django.conf.urls import include, url, patterns
from .allergen import list_allergens

urlpatterns = [
	url(r'^list$', list_allergens, name='allergens'),

]

cooking/inventory/urls.py
from django.conf.urls import include, url, patterns
from .inventory import inventory

urlpatterns = [
	url(r'^list$', inventory, name='inventory'),
]

cooking/project/urls.py
from django.conf.urls import include, url, patterns
from .project import list_projects, new_project, edit_project, del_project

urlpatterns = [
	url(r'^list$', list_projects, name='projects'),
	url(r'^new$', new_project, name='newproject'),
	url(r'^(?P<project>[0-9]+)/edit/$', edit_project, name='editproject'),
	url(r'^(?P<project>[0-9]+)/del/$', del_project, name='delproject'),
]

cooking/recipe/urls.py
from django.conf.urls import include, url, patterns
from .recipe import list_receipes, new_receipe, edit_receipe, del_receipe
from .recipe_ingredient import list_receipe_ingredient

urlpatterns = [
	url(r'^list$', list_receipes, name='receipes'),
	url(r'^new$', new_receipe, name='newreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/edit$', edit_receipe, name='editreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/del$', del_receipe, name='delreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/$', list_receipe_ingredient, name='receipes'),

]

cooking/urls.py
from django.conf.urls import include, url, patterns

urlpatterns = [
	url(r'^project/', include('cooking.project.urls')),
	url(r'^meal/', include('cooking.meal.urls')),
	url(r'^shopping_list/', include('cooking.shopping_list.urls')),
	url(r'^inventory/', include('cooking.inventory.urls')),
	url(r'^recipe/', include('cooking.recipe.urls')),
	url(r'^ingredient/', include('cooking.ingredient.urls')),
	url(r'^allergen/', include('cooking.allergen.urls')),
]

alastair_cookie/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from crispy_forms.bootstrap import FormActions, AppendedText, StrictButton,  InlineField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Field, Hidden, HTML, Div

class MyLoginForm(AuthenticationForm):
	
	def __init__(self, *args, **kwargs):
		super(MyLoginForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-3'
		self.helper.field_class = 'col-lg-6'
		self.helper.layout = Layout(
			'username',
			Field('password'),
			FormActions(Submit('login', 'Login', css_class='btn btn_success')),
			)
			
class MyPasswordChangeForm(PasswordChangeForm):
	
	def __init__(self, *args, **kwargs):
		super(MyPasswordChangeForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-3'
		self.helper.field_class = 'col-lg-6'
		self.helper.layout = Layout(
			'old_password',
			'new_password1',
			'new_password2',
			FormActions(Submit('save', 'Save', css_class='btn btn_success')),
			)
			

alastair_cookie/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

def home(request):
	context = {}
	context['pagetitle'] = 'Home'
	return render(request, 'single/home.html', context)

def tutorial(request):
	context = {}
	context['pagetitle'] = 'Help'
	return render(request, 'single/help.html', context)

def impressum(request):
	context = {}
	context['pagetitle'] = 'Impressum'
	return render(request, 'single/impressum.html', context)

def logout_view(request):
	logout(request)
	return redirect('home')

alastair_cookie/templates/single/confirmdelete.html
{% extends "base_listing.html" %}
{% load crispy_forms_tags %}

{% block bodyform_block %}

	<div class="row placeholders">
		<h2 class="sub-header">Really delete {% firstof object.name objectname %} ?</h2>
		{% crispy form %}
	</div>

{% endblock %}

{% block bodylisting_block %}{% endblock %}

alastair_cookie/templates/single/defaultform.html
{% extends "base_listing.html" %}
{% load crispy_forms_tags %}

{% block bodyform_block %}

	{% if submitted %}
	<div class="alert alert-success" role="alert">Changes saved!</div>
	{% endif %}

	<h1 class="page-header">{{ name }}</h1>

	<div class="row placeholders">
			{% crispy form %}
	</div>


{% endblock %}

{% block bodylisting_block %}{% endblock %}

alastair_cookie/templates/single/help.html
{% extends "base.html" %}

{% block custom_css_block %}
<style>
.important
{
   font-style: italic;
}
</style>
{% endblock %}

{% block body_block %}
<div style="width: 100%; text-align: center">
<h1>What is Alastair</h1>
<div class="well" style="padding-left: 10%; padding-right: 10%;">
	<p>Alastair is an app, with that you can create food plans for events (<a href="{% url 'cooking:projects' %}">projects</a>). It works in two layers: </p>
	<p>At first there are <a href="{% url 'cooking:receipes' %}">receipes</a>, <a href="{% url 'cooking:ingredients' %}">ingredients</a> and <a href="{% url 'cooking:allergens' %}">allergens</a>. These stay the <b>same for all projects</b>, meaning if you create a new project, available receipes and ingredients won't change. 
	Each ingredient has a price, which usually is quite tricky to find out (we went to Aldi and copied the prices from the shelves), but as soon as we have a database, we can use it for all the events. Also, sometimes it is problematic to classify the quantities: in the receipe it may say 100 gram of apples, but you can only buy 12 pieces at once. For this, there is the <span class="important">Calculation Measurement</span>, which can be used as an alternative measurement in the ingredient. But the two measurements available in one ingredient should refer to the same item, meaning if you can buy 2kg of apples, you should put the count of apples in <b>2kg</b> as calculation measurement!</p>
	<p>Then, there are <a href="{% url 'cooking:projects' %}">projects</a>, <a href="{% url 'cooking:receipes' %}">meals</a>, a <a href="{% url 'cooking:shoppinglist' %}">shopping list</a> and an <a href="{% url 'cooking:inventory' %}">inventory</a>, which are only visible when a project is activated. Here, you can define meals which consist of receipes and a person count. So if you want to add a dinner, you can easily change the number of persons you want to cook for. If you want to cook different meals for dinner, like one vegetarian and one omnivor one, you can simply add multiple receipes to the meal, but remember to insert the correct person counts then (you will need to know how many vegetarians there are)</p>
	<p>The really useful thing is the point <span class="important"><a href="{% url 'cooking:shoppinglist' %}">Shopping List</a></span>. Here you can see an autogenerated shopping list for the event: For this, all the ingredients in all the meals are summed up to a <span class="important">Exact Amount</span> of the ingredient. But as you can not buy half a potato, the app also shows an <span class="important">Effective Amount</span>, meaning the amount you can effectively buy in the supermarket. If you already bought something or did good FR, you can add it to the <span class="important"><a href="{% url 'cooking:inventory' %}">Inventory</a></span> and it will be excluded from the shopping list if you activate it</p>
</div>
<h1>Who wrote Alastair</h1>
<div class="well" style="padding-left: 10%; padding-right: 10%;">
	<p>My name is Nico, I am member of AEGEE-Dresden, and because I found it a pain in the a.. to organize and calculate the food for a big event, I wrote this app. Everything is open-source, feel free to use it - just don't sell it. Oh, and I have no real clue why I named this thing <a target="_blank" href="http://muppet.wikia.com/wiki/Alistair_Cookie">Alastair</a></p>
	<p>I am always happy if someone is motivated to help me with the project, check out the <a target="_blank" href="https://github.com/blacksph3re/alastair">github project</a> or contact me! You don't necessarily need to be a programmer, everyone can help!</p>
</div>
</div>
{% endblock %}

alastair_cookie/templates/single/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Alastair cooking app - never worry about cooking for many persons again">
    <meta name="author" content="Nico">
    <!--link rel="icon" href="../../favicon.ico"-->

	<title>{% block title_block %}{{ pagetitle }} - Alastair{% endblock %}</title>

	<!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/cover.css" %}" rel="stylesheet">

   
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Alastair</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'cooking:projects' %}">Cooking</a></li>
                  <li><a href="{% url 'help' %}">Help</a></li>
                  <li><a href="{% url 'impressum' %}">About</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Alastair - The cooking <span class="text-nowrap"><img src="{% static "img/AEGEE-A.png" %}" alt="A" style="width:40px;height:40px;" />pp</span></h1>
            <p class="lead">Proudly presented by <a target="_blank" href="https://www.aegee-dresden.org/">AEGEE-Dresden</a>.</p>
            <p class="lead">
              <a href="{% url "cooking:projects" %}" class="btn btn-lg btn-default">Get Started</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Also on <a target="_blank" href="https://github.com/blacksph3re/alastair">GitHub</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
	<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    {% block custom_script_block %}{% endblock %}    
  </body>
</html>

alastair_cookie/templates/single/impressum.html
{% extends "base.html" %}

{% block custom_css_block %}
<style>
#spammmmer
{
   display: none;
}
</style>
{% endblock %}

{% block body_block %}
<div style="width: 100%; text-align: center">
<h1 style="heading">Impressum</h1>
<p>N<span id="spammmmer">RemoveMe</span>ic<span id="spammmmer">RemoveMe</span>o West<span id="spammmmer">RemoveMe</span>erb<span id="spammmmer">RemoveMe</span>eck</p>
<p>Hein<span id="spammmmer">RemoveMe</span>rich-<span id="spammmmer">RemoveMe</span>Bec<span id="spammmmer">RemoveMe</span>k-Str<span id="spammmmer">RemoveMe</span>aße <span id="spammmmer">RemoveMe</span>5</p>
<p>01<span id="spammmmer">RemoveMe</span>307 Dre<span id="spammmmer">RemoveMe</span>sd<span id="spammmmer">RemoveMe</span>en</p>
<p>Em<span id="spammmmer">RemoveMe</span>ail<span id="spammmmer">RemoveMe</span>: w<span id="spammmmer">RemoveMe</span>este<span id="spammmmer">RemoveMe</span>rbec<span id="spammmmer">RemoveMe</span>k.ni<span id="spammmmer">RemoveMe</span>co@<span id="spammmmer">RemoveMe</span>gma<span id="spammmmer">RemoveMe</span>il.c<span id="spammmmer">RemoveMe</span>om</p>
</div>
{% endblock %}

alastair_cookie/templates/single/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body_block %}
{% if login_failed %}
<div class="alert alert-danger">
Login failed! Did you enter your correct password and username?
</div>

{% endif %}
<div>
	<h1 class="heading">Login</h1>
	{% crispy form %}
</div>
{% endblock %}