alastair_cookie/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home, impressum, logout_view, tutorial
from .forms import MyLoginForm, MyPasswordChangeForm

urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^home/$', home, name='home'),
    url(r'^help/$', tutorial, name='help'),
    url(r'^impressum/$', impressum, name='impressum'),
    url(r'^login/$', auth_views.login, {'authentication_form':MyLoginForm, 'extra_context':{'heading':'Login', 'pagetitle':'Login'}}),
    url(r'^password_change/$', auth_views.password_change, {'template_name':'registration/login.html', 'post_change_redirect':'/password_change/done/', 'password_change_form':MyPasswordChangeForm, 'extra_context':{'heading':'Change Password', 'pagetitle':'Change Password'}}),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^password_change/done/$', auth_views.password_change_done, {'template_name':'registration/login.html', 'extra_context':{'heading':'Password changed', 'message':'Your password was changed successfully!'}}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^', include('cooking.urls', namespace='cooking'), name='cooking'),
    url(r'^$', home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cooking/allergen/urls.py
from django.conf.urls import include, url, patterns
from .allergen import list_allergens

urlpatterns = [
	url(r'^list$', list_allergens, name='allergens'),

]

cooking/meal/urls.py
from django.conf.urls import include, url, patterns
from .meal import list_meals, new_meal, edit_meal, del_meal
from .meal_recipe import list_meal_receipe, meal_receipe_shopping_list

urlpatterns = [
	url(r'^list$', list_meals, name='meals'),
	url(r'^new$', new_meal, name='newmeal'),
	url(r'^(?P<meal>[0-9]+)/$', list_meal_receipe, name='meals'),
	url(r'^(?P<meal>[0-9]+)/edit/$', edit_meal, name='editmeal'),
	url(r'^(?P<meal>[0-9]+)/del/$', del_meal, name='delmeal'),
	url(r'^(?P<meal>[0-9]+)/(?P<receipe>[0-9]+)/$', meal_receipe_shopping_list, name='mrshoppinglist'),


]

cooking/project/urls.py
from django.conf.urls import include, url, patterns
from .project import list_projects, new_project, edit_project, del_project

urlpatterns = [
	url(r'^list$', list_projects, name='projects'),
	url(r'^new$', new_project, name='newproject'),
	url(r'^(?P<project>[0-9]+)/edit/$', edit_project, name='editproject'),
	url(r'^(?P<project>[0-9]+)/del/$', del_project, name='delproject'),
]

cooking/recipe/urls.py
from django.conf.urls import include, url, patterns
from .recipe import list_receipes, new_receipe, edit_receipe, del_receipe
from .recipe_ingredient import list_receipe_ingredient

urlpatterns = [
	url(r'^list$', list_receipes, name='receipes'),
	url(r'^new$', new_receipe, name='newreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/edit$', edit_receipe, name='editreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/del$', del_receipe, name='delreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/$', list_receipe_ingredient, name='receipes'),

]

cooking/urls.py
from django.conf.urls import include, url, patterns

urlpatterns = [
	url(r'^project/', include('cooking.project.urls')),
	url(r'^meal/', include('cooking.meal.urls')),
	url(r'^shopping_list/', include('cooking.shopping_list.urls')),
	url(r'^inventory/', include('cooking.inventory.urls')),
	url(r'^recipe/', include('cooking.recipe.urls')),
	url(r'^ingredient/', include('cooking.ingredient.urls')),
	url(r'^allergen/', include('cooking.allergen.urls')),
]

alastair_cookie/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from crispy_forms.bootstrap import FormActions, AppendedText, StrictButton,  InlineField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Field, Hidden, HTML, Div

class MyLoginForm(AuthenticationForm):
	
	def __init__(self, *args, **kwargs):
		super(MyLoginForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-3'
		self.helper.field_class = 'col-lg-6'
		self.helper.layout = Layout(
			'username',
			Field('password'),
			FormActions(Submit('login', 'Login', css_class='btn btn_success')),
			)
			
class MyPasswordChangeForm(PasswordChangeForm):
	
	def __init__(self, *args, **kwargs):
		super(MyPasswordChangeForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-3'
		self.helper.field_class = 'col-lg-6'
		self.helper.layout = Layout(
			'old_password',
			'new_password1',
			'new_password2',
			FormActions(Submit('save', 'Save', css_class='btn btn_success')),
			)
			

alastair_cookie/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

def home(request):
	context = {}
	context['pagetitle'] = 'Home'
	return render(request, 'single/home.html', context)

def tutorial(request):
	context = {}
	context['pagetitle'] = 'Help'
	return render(request, 'single/help.html', context)

def impressum(request):
	context = {}
	context['pagetitle'] = 'Impressum'
	return render(request, 'single/impressum.html', context)

def logout_view(request):
	logout(request)
	return redirect('home')

alastair_cookie/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!--link rel="icon" href="../../favicon.ico"-->

    <title>{% block title_block %}{{ pagetitle }} - Alastair{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
    
    <!-- Dropdown-Selectbox -->
	<link rel="stylesheet" href="{% static "css/bootstrap-select.css" %}">
	
	{% block custom_css_block %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
   <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">{% block brand_block %}Alastair{% endblock %}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
						
			{% block extra_nav_block %} 
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cooking <span class="caret"></span></a>
				<ul class="dropdown-menu">
					{% if active_page == "projects" %}
						<li class="active"><a href="{% url 'cooking:projects' %}">Overview <span class="sr-only">(current)</span></a></li>
					{% else %}
						<li><a href="{% url 'cooking:projects' %}">Overview</a></li>
					{% endif %}
					
					{% if active_project != None %}
						{% if active_page == "meals" %}
							<li class="active"><a href="{% url 'cooking:meals' %}">Meals <span class="sr-only">(current)</span></a></li>
						{% else %}
							<li><a href="{% url 'cooking:meals' %}">Meals</a></li>
						{% endif %}
					
						{% if active_page == "shoppinglist" %}
							<li class="active"><a href="{% url 'cooking:shoppinglist' %}">Shopping List <span class="sr-only">(current)</span></a></li>
						{% else %}
							<li><a href="{% url 'cooking:shoppinglist' %}">Shopping List</a></li>
						{% endif %}
						
						{% if active_page == "inventory" %}
							<li class="active"><a href="{% url 'cooking:inventory' %}">Inventory <span class="sr-only">(current)</span></a></li>
						{% else %}
							<li><a href="{% url 'cooking:inventory' %}">Inventory</a></li>
						{% endif %}
					{% endif %}
					<li role="seperator" class="divider"></li>
					
					{% if active_page == "receipes" %}
						<li class="active"><a href="{% url 'cooking:receipes' %}">Receipes <span class="sr-only">(current)</span></a></li>
					{% else %}
						<li><a href="{% url 'cooking:receipes' %}">Receipes</a></li>
					{% endif %}
					
					{% if active_page == "ingredients" %}
						<li class="active"><a href="{% url 'cooking:ingredients' %}">Ingredients <span class="sr-only">(current)</span></a></li>
					{% else %}
						<li><a href="{% url 'cooking:ingredients' %}">Ingredients</a></li>
					{% endif %}
					
					{% if active_page == "allergens" %}
						<li class="active"><a href="{% url 'cooking:allergens' %}">Allergens <span class="sr-only">(current)</span></a></li>
					{% else %}
						<li><a href="{% url 'cooking:allergens' %}">Allergens</a></li>
					{% endif %}
				</ul>
			</li>
			{% endblock %}
			
			
            <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user }} <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a href="{% url 'login' %}">Login as another user</a></li>
					<li><a href="{% url 'password_change' %}">Change Password</a></li>
					<li><a href="{% url 'logout' %}">Logout</a></li>
				</ul>
			</li>
			{% else %}
			<li><a href="{% url 'login' %}">Login</a></li>
			{% endif %}
			<li><a href="{% url 'help' %}">Help</a></li>
            <li><a href="{% url 'impressum' %}">Impressum</a></li>
          </ul>
        </div>
        
      </div>
    </nav>

    {% block body_block %}
    
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
    <script src="{% static "js/bootstrap-select.js" %}"></script>
    {% block custom_script_block %}{% endblock %}
  </body>
</html>

alastair_cookie/templates/base_listing.html
{% extends "base.html" %}
{% load static %}

{% block brand_block %}Alastair ({% firstof active_project.name 'No Project active' %}){% endblock %}


{% block body_block %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
          
          {% if active_page == "projects" %}
            <li class="active"><a href="{% url 'cooking:projects' %}">Overview <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li><a href="{% url 'cooking:projects' %}">Overview</a></li>
	      {% endif %}
	      
	      {% if active_project != None %}
			{% if active_page == "meals" %}
				<li class="active"><a href="{% url 'cooking:meals' %}">Meals <span class="sr-only">(current)</span></a></li>
			{% else %}
				<li><a href="{% url 'cooking:meals' %}">Meals</a></li>
			{% endif %}
		 
			{% if active_page == "shoppinglist" %}
				<li class="active"><a href="{% url 'cooking:shoppinglist' %}">Shopping List <span class="sr-only">(current)</span></a></li>
			{% else %}
				<li><a href="{% url 'cooking:shoppinglist' %}">Shopping List</a></li>
			{% endif %}
			
			{% if active_page == "inventory" %}
				<li class="active"><a href="{% url 'cooking:inventory' %}">Inventory <span class="sr-only">(current)</span></a></li>
			{% else %}
				<li><a href="{% url 'cooking:inventory' %}">Inventory</a></li>
			{% endif %}
	      {% endif %}
          </ul>
          <ul class="nav nav-sidebar">
          
          {% if active_page == "receipes" %}
            <li class="active"><a href="{% url 'cooking:receipes' %}">Receipes <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li><a href="{% url 'cooking:receipes' %}">Receipes</a></li>
	      {% endif %}
          
          {% if active_page == "ingredients" %}
            <li class="active"><a href="{% url 'cooking:ingredients' %}">Ingredients <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li><a href="{% url 'cooking:ingredients' %}">Ingredients</a></li>
	      {% endif %}
	      
	      {% if active_page == "allergens" %}
            <li class="active"><a href="{% url 'cooking:allergens' %}">Allergens <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li><a href="{% url 'cooking:allergens' %}">Allergens</a></li>
	      {% endif %}
          
          </ul>
        </div>
       <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
		 {% block bodyform_block %}{% endblock %}
<!--       <h1 class="page-header">Dashboard</h1>

           <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
           </div> -->
           
          {% block bodylisting_block %}<h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>{% endblock %}
        </div>
      </div>
    </div>
{% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
    <script src="{% static "js/bootstrap-select.js" %}"></script>
    <script>
		$(document).ready(function(){$('[data-toggle="tooltip"]').tooltip();});
    </script>
    {% block custom_script_block %}{% endblock %}
  </body>
</html>

alastair_cookie/templates/date.html
{% load crispy_forms_field %}

<div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %} {% if field.field.widget.attrs.class %} {{ field.field.widget.attrs.class }}{% endif %}">

    {% if field.label %}
        <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    <div class="controls">
        <div class="input-append">
            {% crispy_field field %}
            <span class="add-on {% if active %}active{% endif %}">{{ crispy_appended_text|safe }}</span>
        </div>

        {% include 'bootstrap/layout/help_text_and_errors.html' %}
    </div>
</div>

<!-- 

To be used with bootstrap-datepicker and Django DateField. 
http://www.eyecon.ro/bootstrap-datepicker/

In your layout do: `Field('field_name', template='date.html')`

Make sure date.html is in your templates path. You could build a custom layout object inheriting from `Field` named `DateField` that could get parameters passed for `data-date` and `data-date-format` for example.

-->