alastair_cookie/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home, impressum, logout_view, tutorial
from .forms import MyLoginForm, MyPasswordChangeForm

urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^home/$', home, name='home'),
    url(r'^help/$', tutorial, name='help'),
    url(r'^impressum/$', impressum, name='impressum'),
    url(r'^login/$', auth_views.login, {'authentication_form':MyLoginForm, 'extra_context':{'heading':'Login', 'pagetitle':'Login'}}),
    url(r'^password_change/$', auth_views.password_change, {'template_name':'registration/login.html', 'post_change_redirect':'/password_change/done/', 'password_change_form':MyPasswordChangeForm, 'extra_context':{'heading':'Change Password', 'pagetitle':'Change Password'}}),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^password_change/done/$', auth_views.password_change_done, {'template_name':'registration/login.html', 'extra_context':{'heading':'Password changed', 'message':'Your password was changed successfully!'}}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^', include('cooking.urls', namespace='cooking'), name='cooking'),
    url(r'^$', home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cooking/ingredient/urls.py
from django.conf.urls import include, url, patterns
from .ingredient import list_ingredients, ingredients_csv, edit_ingredient, del_ingredient, new_ingredient

urlpatterns = [
	url(r'^list$', list_ingredients, name='ingredients'),
	url(r'^download.csv$', ingredients_csv, name='ingredientscsv'),
	url(r'^(?P<ingredient>[0-9]+)/edit$', edit_ingredient, name='ingredients'),
	url(r'^(?P<ingredient>[0-9]+)/del$', del_ingredient, name='delingredient'),
	url(r'^new/$', new_ingredient, name='newingredient'),

]

cooking/meal/urls.py
from django.conf.urls import include, url, patterns
from .meal import list_meals, new_meal, edit_meal, del_meal
from .meal_recipe import list_meal_receipe, meal_receipe_shopping_list

urlpatterns = [
	url(r'^list$', list_meals, name='meals'),
	url(r'^new$', new_meal, name='newmeal'),
	url(r'^(?P<meal>[0-9]+)/$', list_meal_receipe, name='meals'),
	url(r'^(?P<meal>[0-9]+)/edit/$', edit_meal, name='editmeal'),
	url(r'^(?P<meal>[0-9]+)/del/$', del_meal, name='delmeal'),
	url(r'^(?P<meal>[0-9]+)/(?P<receipe>[0-9]+)/$', meal_receipe_shopping_list, name='mrshoppinglist'),


]

cooking/project/urls.py
from django.conf.urls import include, url, patterns
from .project import list_projects, new_project, edit_project, del_project

urlpatterns = [
	url(r'^list$', list_projects, name='projects'),
	url(r'^new$', new_project, name='newproject'),
	url(r'^(?P<project>[0-9]+)/edit/$', edit_project, name='editproject'),
	url(r'^(?P<project>[0-9]+)/del/$', del_project, name='delproject'),
]

cooking/recipe/urls.py
from django.conf.urls import include, url, patterns
from .recipe import list_receipes, new_receipe, edit_receipe, del_receipe
from .recipe_ingredient import list_receipe_ingredient

urlpatterns = [
	url(r'^list$', list_receipes, name='receipes'),
	url(r'^new$', new_receipe, name='newreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/edit$', edit_receipe, name='editreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/del$', del_receipe, name='delreceipe'),
	url(r'^(?P<active_receipe>[0-9]+)/$', list_receipe_ingredient, name='receipes'),

]

cooking/shopping_list/urls.py
from django.conf.urls import include, url, patterns
from .shopping_list import project_shopping_list, project_shopping_list_csv

urlpatterns = [
	url(r'^list$', project_shopping_list, name='shoppinglist'),
	url(r'^download.csv$', project_shopping_list_csv, name='shoppinglistcsv'),
]

cooking/urls.py
from django.conf.urls import include, url, patterns

urlpatterns = [
	url(r'^project/', include('cooking.project.urls')),
	url(r'^meal/', include('cooking.meal.urls')),
	url(r'^shopping_list/', include('cooking.shopping_list.urls')),
	url(r'^inventory/', include('cooking.inventory.urls')),
	url(r'^recipe/', include('cooking.recipe.urls')),
	url(r'^ingredient/', include('cooking.ingredient.urls')),
	url(r'^allergen/', include('cooking.allergen.urls')),
]

cooking/models/allergen.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Field, Hidden, HTML, Div
from crispy_forms.bootstrap import FormActions, AppendedText, StrictButton,  InlineField
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import resolve, reverse
from django.db import models
from django.db.models import F, ExpressionWrapper, FloatField, IntegerField, CharField, Case, When, Sum, Func, Min, Q
from django.shortcuts import render, redirect
from django.utils.encoding import python_2_unicode_compatible
from .helpers import prepareContext


@python_2_unicode_compatible
class Allergen(models.Model):
	name = models.CharField(max_length=256)
	def __str__(self):
		return self.name
	
	class Meta:
		ordering = ['name']
		
	
@login_required
def list_allergens(request):
	context = prepareContext(request)
	
	if('remove_allergen' in request.GET):
		try:
			Allergen.objects.get(id=int(request.GET.get('remove_allergen'))).delete()
		except:
			pass
	
	form = AllergenForm(request.POST or None)
	if(form.is_valid()):
		form.save()
		form = AllergenForm(None)
	
	context['form'] = form
	context['allergen_list'] = Allergen.objects.all()
	context['pagetitle'] = 'Allergens'
	return render(request, 'listings/allergens.html', context)

cooking/models/ingredient.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Field, Hidden, HTML, Div
from crispy_forms.bootstrap import FormActions, AppendedText, StrictButton,  InlineField
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import resolve, reverse
from django.db import models
from django.db.models import F, ExpressionWrapper, FloatField, IntegerField, CharField, Case, When, Sum, Func, Min, Q
from django.shortcuts import render, redirect
from django.utils.encoding import python_2_unicode_compatible
from .helpers import prepareContext


@python_2_unicode_compatible
class Ingredient(models.Model):
	name = models.CharField(max_length=256)
	buying_quantity = models.FloatField(validators=[validate_greater_zero])
	buying_measurement = models.CharField(max_length=2, choices=MEASUREMENTS)
	calculation_quantity = models.FloatField(blank=True, null=True, validators=[validate_greater_zero])
	calculation_measurement = models.CharField(max_length=2, choices=MEASUREMENTS, blank=True, null=True)	
	price = models.DecimalField(max_digits=8, decimal_places=2, validators=[validate_positive])
	cheapest_store = models.CharField(max_length=256, blank=True)
	remarks = models.CharField(max_length=256, blank=True)
	allergens = models.ManyToManyField(Allergen, blank=True)
	cooked_weight = models.FloatField(default=0, validators=[validate_positive])

	def __str__(self):
		return self.name
	
	class Meta:
		ordering = ['name']
	

@login_required
def list_ingredients(request):
	context = prepareContext(request)
	context['ingredient_list'] = Ingredient.objects.all()
	context['pagetitle'] = 'Ingredients'
	return render(request, 'listings/ingredients.html', context)

@login_required
def edit_ingredient(request, ingredient):
	context = prepareContext(request)
	if(request.POST and 'id' in request.POST):
		ingredient = int(request.POST.get('id'))
	ing = Ingredient.objects.get(id=ingredient)
	form = IngredientForm(request.POST or None, instance=ing)
	if(form.is_valid()):
		form.save()
		context['submitted'] = True
	context['form'] = form
	context['name'] = ing.name
	context['pagetitle'] = 'Edit Ingredient'
	return render(request, 'single/defaultform.html', context)

@login_required
def del_ingredient(request, ingredient):
	context = prepareContext(request)
	ing = Ingredient.objects.get(id=ingredient)
	form = ConfirmDeleteForm(request.POST or None)
	if(form.is_valid()):
		ing.delete()
		return redirect('cooking:ingredients')
	
	context['object'] = ing
	context['noaction'] = reverse('cooking:ingredients')
	context['form'] = form
	context['pagetitle'] = 'Delete Ingredient'
	return render(request, 'single/confirmdelete.html', context)

@login_required
def new_ingredient(request):
	context = prepareContext(request)
	form = None
	if(request.POST):
		form = IngredientForm(data=request.POST or None)
		if(form.is_valid()):
			form.save()
			return redirect('cooking:ingredients')
	else:
		form = IngredientForm()
	
	context['form'] = form
	context['name'] = 'New Ingredient'
	context['pagetitle'] = 'New Ingredient'
	return render(request, 'single/defaultform.html', context)
	

@login_required
def ingredients_csv(request):
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="ingredients.csv"'
	writer = UnicodeWriter(response)
	writer.writerow(['Name', 'Buying unit', '', 'Calculation unit', '', 'Price', 'Remarks', 'Cheapest Store', 'Allergens'])
	ingredients = Ingredient.objects.all()
	for item in ingredients:
		writer.writerow([item.name,
				   item.buying_quantity,
				   conv_measurement(item.buying_measurement, item.buying_quantity),
				   item.calculation_quantity,
				   conv_measurement(item.calculation_measurement, item.calculation_quantity),
				   item.price,
				   item.remarks,
				   item.cheapest_store,
				   ', '.join([a.name for a in item.allergens.all()])])
	
	return response
	

cooking/models/meal.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Field, Hidden, HTML, Div
from crispy_forms.bootstrap import FormActions, AppendedText, StrictButton,  InlineField
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import resolve, reverse
from django.db import models
from django.db.models import F, ExpressionWrapper, FloatField, IntegerField, CharField, Case, When, Sum, Func, Min, Q
from django.shortcuts import render, redirect
from django.utils.encoding import python_2_unicode_compatible
from .helpers import prepareContext

@python_2_unicode_compatible
class Meal(models.Model):
	name = models.CharField(max_length=256)
	time = models.DateTimeField(blank=True, null=True)
	project = models.ForeignKey(Project)
	used_receipes = models.ManyToManyField(Receipe, through='Meal_Receipe', blank=True)
	
	def __str__(self):
		return self.name
	
	class Meta:
		ordering = ['time', 'name']
		
		
			
class MealForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(MealForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-2'
		self.helper.field_class = 'col-lg-4'
		self.helper.layout = Layout(
				'name',
				Field('time', placeholder='yyyy-mm-dd hh:mm'),
				Field('project', required=True),
				FormActions(
					Submit('save', 'Save Changes'),
					HTML('<a href="' + reverse('cooking:meals') + '" class="btn btn-default" role="button">Cancel</a>'),
					HTML('{% if meal.id %}<a href="{% url "cooking:meals" meal.id %}" class="btn btn-default" role="button">Choose Receipe</a>{% endif %}')
					)
		)	
	class Meta:
		model = Meal
		exclude = ['used_receipes', 'project']
	
	
@login_required
def list_meals(request):
	context = prepareContext(request)
	if('active_project' not in context):
		return redirect('cooking:projects')
	context['meals_list'] = Meal.objects.filter(project=context['active_project'])
	context['pagetitle'] = 'Meals'
	return render(request, 'listings/meals.html', context)

@login_required
def edit_meal(request, meal):
	context = prepareContext(request)
	if(request.POST and 'id' in request.POST):
		meal = int(request.POST.get('id'))
	m = Meal.objects.get(id=meal)
	form = MealForm(request.POST or None, instance=m)
	if(form.is_valid()):
		form.save()
		context['submitted'] = True
	context['form'] = form
	context['meal'] = m
	context['name'] = m.name
	context['pagetitle'] = 'Edit Meal'
	return render(request, 'single/defaultform.html', context)

@login_required
def del_meal(request, meal):
	context = prepareContext(request)
	m = Meal.objects.get(id=meal)
	form = ConfirmDeleteForm(request.POST or None)
	if(form.is_valid()):
		m.delete()
		return redirect('cooking:meals')
	
	context['object'] = m
	context['noaction'] = reverse('cooking:meals')
	context['form'] = form
	context['pagetitle'] = 'Delete Meal'
	return render(request, 'single/confirmdelete.html', context)

@login_required
def new_meal(request):
	context = prepareContext(request)
	form = None
	meal = Meal(project=context['active_project'])
	if(request.POST):
		form = MealForm(data=request.POST or None, instance=meal)
		if(form.is_valid()):
			form.save()
			return redirect('cooking:meals')
	else:
		form = MealForm(instance=meal)
	
	context['form'] = form
	context['name'] = 'New Meal'
	context['pagetitle'] = 'New Meal'
	return render(request, 'single/defaultform.html', context)

alastair_cookie/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from crispy_forms.bootstrap import FormActions, AppendedText, StrictButton,  InlineField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Field, Hidden, HTML, Div

class MyLoginForm(AuthenticationForm):
	
	def __init__(self, *args, **kwargs):
		super(MyLoginForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-3'
		self.helper.field_class = 'col-lg-6'
		self.helper.layout = Layout(
			'username',
			Field('password'),
			FormActions(Submit('login', 'Login', css_class='btn btn_success')),
			)
			
class MyPasswordChangeForm(PasswordChangeForm):
	
	def __init__(self, *args, **kwargs):
		super(MyPasswordChangeForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = ''
		self.helper.label_class = 'col-lg-3'
		self.helper.field_class = 'col-lg-6'
		self.helper.layout = Layout(
			'old_password',
			'new_password1',
			'new_password2',
			FormActions(Submit('save', 'Save', css_class='btn btn_success')),
			)
			

alastair_cookie/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

def home(request):
	context = {}
	context['pagetitle'] = 'Home'
	return render(request, 'single/home.html', context)

def tutorial(request):
	context = {}
	context['pagetitle'] = 'Help'
	return render(request, 'single/help.html', context)

def impressum(request):
	context = {}
	context['pagetitle'] = 'Impressum'
	return render(request, 'single/impressum.html', context)

def logout_view(request):
	logout(request)
	return redirect('home')

alastair_cookie/templates/listings/ingredients.html
{% extends "base_listing.html" %}

{% block bodylisting_block %}<h2 class="sub-header">Available Ingredients <a href="{% url 'cooking:ingredientscsv' %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Download as .csv"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span><span class="sr-only">Download</span></a></h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
		<tr>
			<th>Name</th>
			<th>Buying unit</th>
			<th>Calculation unit</th>
			<th>Price</th>
			<th>Remarks</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		{% for ing in ingredient_list %}
			<tr class="{% cycle 'odd' 'even' %}">
				<td><a href="{% url 'cooking:ingredients' ing.id %}">{{ ing.name }}</a></td>
				{% if ing.buying_measurement == 'n' %}
				<td>{{ ing.buying_quantity|floatformat }} piece{{ ing.buying_quantity|pluralize }}</td>
				{% else %}
				<td>{{ ing.buying_quantity|floatformat }}{{ ing.buying_measurement }}</td>
				{% endif %}
				{% if ing.calculation_measurement == 'n' %}
				<td>{{ ing.calculation_quantity|default:'-'|floatformat }} piece{{ ing.calculation_quantity|pluralize }}</td>
				{% else %}
				<td>{{ ing.calculation_quantity|default:'-'|floatformat }}{{ ing.calculation_measurement|default:'' }}</td>
				{% endif %}
				<td>{{ ing.price|floatformat:2 }}€</td>
				<td>{{ ing.remarks }}</td>
				<td><span class="text-nowrap">
					<a href="{% url "cooking:delingredient" ing.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Delete ingredient {{ ing.name }}"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span><span class="sr-only">Del</span></a>
					<a href="{% url "cooking:ingredients" ing.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Edit ingredient {{ ing.name }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="sr-only">Edit</span></a>
				</span></td>
			</tr>		
		{% endfor %}
		<tr><td></td><td></td><td></td><td></td><td></td>
			<td><a href="{% url "cooking:newingredient" %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Add a new ingredient"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="sr-only">Add</span></a>

		</tr>
		</tbody>
	</table>
</div>
{% endblock %}

alastair_cookie/templates/listings/meal_receipe.html
{% extends "base_listing.html" %}
{% load crispy_forms_tags %}

{% block bodylisting_block %}
{% for key in form.errors %}
<div class="alert alert-danger">
	Error in Field "{{ key|title }}":
	{{ form.errors|get_item:key }}

</div>
{% endfor %}

<h2 class="sub-header">Used receipes in meal {{ meal.name }}</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
		<tr>
			<th>Receipe</th>
			<th>Person Count</th>
			<th>Price per Person</th>
			<th>Weight per Person</th>
			<th>Remarks</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		{% for rec in meal_receipe_list %}
			<tr>
				<td><a href="{% url 'cooking:mrshoppinglist' meal.id rec.receipe.id %}">{{ rec.receipe.name }}</a></td>
				
				<td>{{ rec.person_count }}</td>
				
				<td>{% if rec.price_per_person %}{{ rec.price_per_person|floatformat:2 }}&euro;{% endif %}</td>
				
				<td>{% if rec.weight_per_person %}{{ rec.weight_per_person|floatformat }} gram{% endif %}</td>
				
				<td>{{ rec.remarks }}</td>
				
				<td><span class="text-nowrap">
					<a href="{{ request.path|urlencode }}?remove_meal_receipe={{ rec.id }}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span><span class="sr-only">Del</span></a>
					<a href="{% url "cooking:receipes" rec.receipe.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="View and edit ingredients of receipe {{ rec.receipe.name }}"><span class="glyphicon glyphicon-list" aria-hidden="true"></span><span class="sr-only">Info</span></a>
					<a href="{% url 'cooking:mrshoppinglist' meal.id rec.receipe.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="View a shopping list of only this receipe"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span><span class="sr-only">Info</span></a>
					
				</span></td>
			</tr>		
		{% endfor %}
		<tr>
			
			{% crispy form %}

		</tr>
		</tbody>
	</table>
</div>

{% endblock %}

alastair_cookie/templates/listings/meals.html
{% extends "base_listing.html" %}

{% block bodylisting_block %}<h2 class="sub-header">Meals in Project {{ active_project.name }}</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
		<tr>
			<th>Name</th>
			<th>Time</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		{% for meal in meals_list %}
			<tr class="{% cycle 'odd' 'even' %}">
				<td><a href="{% url "cooking:meals" meal.id %}">{{ meal.name }}</a></td>
				<td>{{ meal.time }}</td>
				<td><span class="text-nowrap">
					<a href="{% url "cooking:delmeal" meal.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Delete meal {{ meal.name }}"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span><span class="sr-only">Del</span></a>
					<a href="{% url "cooking:editmeal" meal.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Edit meal {{ meal.name }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="sr-only">Edit</span></a>
					<a href="{% url "cooking:meals" meal.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="View and edit receipes in meal {{ meal.name }}"><span class="glyphicon glyphicon-list" aria-hidden="true"></span><span class="sr-only">Del</span></a>
				</span></td>
			</tr>		
		{% endfor %}
		<tr><td></td><td></td>
			<td><a href="{% url "cooking:newmeal" %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Add a new meal"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="sr-only">Add</span></a></td>
		</tr>
		</tbody>
	</table>
</div>
{% endblock %}

alastair_cookie/templates/listings/projects.html
{% extends "base_listing.html" %}

{% block bodylisting_block %}<h2 class="sub-header">Projects</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
		<tr>
			<th>Name</th>
			<th>Starting</th>
			<th>Ending</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		{% for proj in project_list %}
			<tr class="{% cycle 'odd' 'even' %}">
				<td><a href="{% url 'cooking:meals' %}?activate_project={{ proj.id }}">{{ proj.name }}{% if proj == active_project %} (active){% endif %}</a></td>
				<td>{{ proj.start_date }}</td>
				<td>{{ proj.end_date }}</td>
				<td><span class="text-nowrap">
					<a href="{% url 'cooking:delproject' proj.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Delete project {{ proj.name }}"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span><span class="sr-only">Del</span></a>
					<a href="{% url 'cooking:editproject' proj.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Edit project {{ proj.name }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="sr-only">Edit</span></a>
					{% if proj == active_project %}
					<a href="{% url 'cooking:projects' %}?activate_project=none" class="btn btn-default btn-sm" data-toggle="tooltip" title="Deactivate project {{ proj.name }}"><span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span><span class="sr-only">Deactivate</span></a>
					{% else %}
					<a href="{% url 'cooking:projects' %}?activate_project={{ proj.id }}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Activate project {{ proj.name }}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span><span class="sr-only">Activate</span></a>
					{% endif %}
				</span></td>
			</tr>		
		{% endfor %}
		<tr>
			<td></td><td></td><td></td>
			<td>
				<a href="{% url 'cooking:newproject' %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Add a new project"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="sr-only">Add</span></a>
			</td>
		</tr>
		</tbody>
	</table>
</div>
{% endblock %}

alastair_cookie/templates/listings/propose_receipes.html
{% extends "base_listing.html" %}
{% load crispy_forms_tags %}

{% block bodylisting_block %}



{% endblock %}

alastair_cookie/templates/listings/receipes.html
{% extends "base_listing.html" %}

{% block bodylisting_block %}<h2 class="sub-header">Available Receipes</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
		<tr>
			<th>Name</th>
			<th>Default Person Count</th>
			<th>Price per Person</th>
			<th>Weight per Person</th>
			<th></th>
		</tr>
		</thead>
		<tbody>
		{% for rec in receipe_list %}
			<tr class="{% cycle 'odd' 'even' %}">
				<td><a href="{% url "cooking:receipes" rec.id %}">{{ rec.name }}</a></td>
				<td>{{ rec.default_person_count }}</td>
				<td>{% if rec.price_per_person %}{{ rec.price_per_person|floatformat:2 }}&euro;{% endif %}</td>
				<td>{% if rec.weight_per_person %}{{ rec.weight_per_person|floatformat }} gram {% endif %}</td>
				<td><span class="text-nowrap">
					<a href="{% url "cooking:delreceipe" rec.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Delete receipe {{ rec.name }}"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span><span class="sr-only">Del</span></a>
					<a href="{% url "cooking:editreceipe" rec.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Edit receipe {{ rec.name }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="sr-only">Edit</span></a>
					<a href="{% url "cooking:receipes" rec.id %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="View and edit ingredients in receipe {{ rec.name }}"><span class="glyphicon glyphicon-list" aria-hidden="true"></span><span class="sr-only">Del</span></a>
				</span></td>
			</tr>		
		{% endfor %}
		<tr><td></td><td></td><td></td><td></td>
			<td><a href="{% url "cooking:newreceipe" %}" class="btn btn-default btn-sm" data-toggle="tooltip" title="Add a new receipe"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="sr-only">Add</span></a>
		</tr>
		</tbody>
	</table>
</div>
{% endblock %}